# CHATBOT

#Car price prediction model ML

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
#Read CSV File
cars_df = pd.read_csv("Resources/cars_info.csv")
cars_df.head()

ID                                               Name   Price  \
0  11530130                  2010 Toyota Rukus Build 2 AZE151R    9999   
1  12190570  2021 Mercedes-Benz V 250 D Avantgarde MWB 447 ...  117990   
2  12321855  2021 Mercedes-Benz Valente 116 CDI MWB RWD 447...   79990   
3  12346971         2010 Mercedes-Benz E250 CDI Avantgarde 207   34990   
4  12363884                       2016 Holden Cruze CD JH MY16   15990   

           Brand    Model               Variant    Series  Year  Kilometers  \
0         Toyota    Rukus               Build 2   AZE151R  2010      263000   
1  Mercedes-Benz        V  250 D Avantgarde MWB  447 MY21  2021          19   
2  Mercedes-Benz  Valente       116 CDI MWB RWD  447 MY21  2021          24   
3  Mercedes-Benz     E250        CDI Avantgarde       207  2010      120579   
4         Holden    Cruze                    CD   JH MY16  2016       72506   

          Type    Gearbox             Fuel         Status    CC  Color  \
0        Wagon  Automatic  Unleaded Petrol           Used  2362   Grey   
1        Wagon  Automatic           Diesel   New In Stock  2143  Black   
2        Wagon  Automatic           Diesel   New In Stock  2143  Black   
3    Cabriolet  Automatic           Diesel           Used  2143  Black   
4  Sportswagon  Automatic  Unleaded Petrol           Used  1796  White   

   Seating Capacity  
0                 5  
1                 7  
2                 8  
3                 4  
4                 5

In [3]:
cars_df.info()



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17048 entries, 0 to 17047
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   ID                17048 non-null  int64 
 1   Name              17048 non-null  object
 2   Price             17048 non-null  int64 
 3   Brand             17048 non-null  object
 4   Model             17048 non-null  object
 5   Variant           17048 non-null  object
 6   Series            17048 non-null  object
 7   Year              17048 non-null  int64 
 8   Kilometers        17048 non-null  int64 
 9   Type              17048 non-null  object
 10  Gearbox           17048 non-null  object
 11  Fuel              17048 non-null  object
 12  Status            17048 non-null  object
 13  CC                17048 non-null  int64 
 14  Color             17048 non-null  object
 15  Seating Capacity  17048 non-null  int64 
dtypes: int64(6), object(10)
memory usage: 2.1+ MB


In [4]:
#Duplicate values
duplicate = cars_df.duplicated().sum()
print(f'number of duplicate rows are {duplicate}')

number of duplicate rows are 0


In [5]:
#Data Analysis
for col in cars_df.columns:
    print('Unique values of' + col)
    print(cars_df[col].unique())
    print("--------------------------------------------")

Unique values ofID
[11530130 12190570 12321855 ... 12852462 12852463 12852464]
--------------------------------------------
Unique values ofName
['2010 Toyota Rukus Build 2 AZE151R'
 '2021 Mercedes-Benz V 250 D Avantgarde MWB 447 MY21'
 '2021 Mercedes-Benz Valente 116 CDI MWB RWD 447 MY21' ...
 '2015 Land Rover Discovery 4 3.0 SDV6 HSE MY15'
 '2002 Holden Jackaroo SE LWB (4X4) U8'
 '2005 Toyota RAV4 Cruiser (4X4) ACA23R']
--------------------------------------------
Unique values ofPrice
[  9999 117990  79990 ...  31962  26992  35992]
--------------------------------------------
Unique values ofBrand
['Toyota' 'Mercedes-Benz' 'Holden' 'Nissan' 'Ford' 'BMW' 'Isuzu' 'Hyundai'
 'Volkswagen' 'Lexus' 'Mazda' 'Audi' 'Subaru' 'Mitsubishi' 'Kia' 'Skoda'
 'Renault' 'Porsche' 'Jeep' 'Honda' 'Ssangyong' 'Volvo' 'Land Rover' 'MG'
 'Suzuki' 'Ram' 'Mini' 'Jaguar' 'LDV' 'HSV' 'Alfa Romeo' 'Aston Martin'
 'Hino' 'Chrysler' 'Citroen' 'Infiniti' 'Peugeot' 'Chevrolet'
 'Lamborghini' 'Fiat' 'Bentley' 'Dod

In [6]:
cars_df.drop(columns=['ID','Model', 'Name'], inplace=True)
cars_df.head()


Price          Brand               Variant    Series  Year  Kilometers  \
0    9999         Toyota               Build 2   AZE151R  2010      263000   
1  117990  Mercedes-Benz  250 D Avantgarde MWB  447 MY21  2021          19   
2   79990  Mercedes-Benz       116 CDI MWB RWD  447 MY21  2021          24   
3   34990  Mercedes-Benz        CDI Avantgarde       207  2010      120579   
4   15990         Holden                    CD   JH MY16  2016       72506   

          Type    Gearbox             Fuel         Status    CC  Color  \
0        Wagon  Automatic  Unleaded Petrol           Used  2362   Grey   
1        Wagon  Automatic           Diesel   New In Stock  2143  Black   
2        Wagon  Automatic           Diesel   New In Stock  2143  Black   
3    Cabriolet  Automatic           Diesel           Used  2143  Black   
4  Sportswagon  Automatic  Unleaded Petrol           Used  1796  White   

   Seating Capacity  
0                 5  
1                 7  
2                 8  
3                 4  
4                 5

In [7]:

from sklearn.preprocessing import LabelEncoder, OneHotEncoder


# Load dataset (assuming `cars_df` is already loaded)
# Define Features (X) and Target (y)
X = cars_df.drop(columns=['Price'])  
y = cars_df['Price']

# Identify categorical columns
categorical_cols = ['Brand', 'Variant', 'Series', 'Year', 'Type', 'Gearbox', 'Fuel', 'Status', 'Color']

# Applied Label Encoding 
encoder = LabelEncoder()
for col in categorical_cols:
    X[col] = encoder.fit_transform(X[col])

# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train Model
model = LinearRegression()
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

print("Model training complete!")



Model training complete!


#Linear Regression

In [8]:
predict = model.predict(X_test)
predict

array([34332.78916002, 60022.35759088, 22704.05251298, ...,
       47107.41755234, 64280.5088809 , 36234.09781938])

In [15]:
X_train.head(2)


Brand  Variant  Series  Year  Kilometers  Type  Gearbox  Fuel  Status  \
7720     57     1497      58    23      108607    11        1     3       2   
6627     51     1904    1557    33           9    52        1     5       1   

        CC  Color  Seating Capacity  
7720  1984     16                 4  
6627  1395    166                 5

In [16]:
input_data_model = pd.DataFrame(
    [[57,1497,58,23,108607,11,1,3,2,1984,16,4]],
    columns=['Brand', 'Variant', 'Series',	'Year',	'Kilometers',	'Type',	'Gearbox',	'Fuel',	'Status',	'CC',	'Color',	'Seating Capacity'])

In [17]:
model.predict(input_data_model)

array([30611.02721994])

In [18]:
import pickle as pk

In [19]:
pk.dump(model,open('model.pkl','wb'))